service:
  name: positive-devices

plugins:
  - serverless-domain-manager
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - webpack-node-externals

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  deploymentBucket:
    name: "serverless"


custom:
  webpack:
    includeModules:
      forceInclude:
        - read-chunk
    packager: 'yarn'
  serverless-offline:
    port: 3003
  subdomain:
    dev: 'dev.'
    staging: 'staging.'
    production: ''
  customDomain:
    domainName: "api.${self:custom.subdomain.${opt:stage, 'dev.'}}positive-devices.com"
    basePath: "v1"
    stage: ${opt:stage, self:provider.stage}
    createRoute53Record: true
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
          port: 8000
          inMemory: true
          heapInitial: 200m
          heapMax: 1g
          migrate: true
          seed: true
          convertEmptyValues: true


functions:
  add:
    handler: src/index.add
    timeout: 900
    memorySize: 256
    reservedConcurrency: 20
    events:
      - http:
          cors: true
          path: add
          method: post
          request:
            parameters:
              querystrings:
                ida: true
                idb: true


resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: EntryType
            AttributeType: S
          -
            AttributeName: Id1
            AttributeType: S
          -
            AttributeName: Id2
            AttributeType: S
          -
            AttributeName: timestamp
            AttributeType: N
        KeySchema:
          -
            AttributeName: EntryType
            KeyType: HASH
          -
            AttributeName: Id1
            KeyType: HASH
          -
            AttributeName: Id2
            KeyType: HASH
          -
            AttributeName: Timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: Entry
